





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace dev.joestevens.web.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}

namespace dev.joestevens.web.Models.sitecore.templates.Custom.Services
{


 	/// <summary>
	/// IService Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Custom/Services/Service</para>	
	/// <para>ID: d7d6320f-1b5b-4305-8624-9f3c507a35ba</para>	
	/// </summary>
	[SitecoreType(TemplateId=IServiceConstants.TemplateIdString )] //, Cachable = true
	public partial interface IService : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 3c26c0f1-2b54-4217-8507-31837b80b248</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Text field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: b99b88b5-681a-4ee3-91d1-74fb5f316c3e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.TextFieldName)]
					string Text  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 1d49f236-92a2-4fde-ac9a-db8b85b5a167</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IServiceConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IServiceConstants{

			public const string TemplateIdString = "d7d6320f-1b5b-4305-8624-9f3c507a35ba";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Service";

					
			public static readonly ID ImageFieldId = new ID("3c26c0f1-2b54-4217-8507-31837b80b248");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID TextFieldId = new ID("b99b88b5-681a-4ee3-91d1-74fb5f316c3e");
			public const string TextFieldName = "Text";
			
					
			public static readonly ID TitleFieldId = new ID("1d49f236-92a2-4fde-ac9a-db8b85b5a167");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Service
	/// <para></para>
	/// <para>Path: /sitecore/templates/Custom/Services/Service</para>	
	/// <para>ID: d7d6320f-1b5b-4305-8624-9f3c507a35ba</para>	
	/// </summary>
	[SitecoreType(TemplateId=IServiceConstants.TemplateIdString)] //, Cachable = true
	public partial class Service  : GlassBase, IService 
	{
	   
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 3c26c0f1-2b54-4217-8507-31837b80b248</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Text field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: b99b88b5-681a-4ee3-91d1-74fb5f316c3e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 1d49f236-92a2-4fde-ac9a-db8b85b5a167</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IServiceConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
